language: go
sudo: false
go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

before_script:
  - mysql -e 'create database gotest;'

script:
  - ./test.sh 

after_success:
  - bash <(curl -s https://codecov.io/bash)
