language: go
sudo: false
go:
  - 1.5
  - 1.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "create database IF NOT EXISTS gotest;" -uroot

script:
  - ./test.sh 

after_success:
  - bash <(curl -s https://codecov.io/bash)
